language: python
dist: xenial
python:
  - "3.6"
jobs:
  include:
    - stage: linting
      install:
        - pip install flake8
      script:
        - flake8
    - stage: integrity_tests
      install:
        - pip install -r integrity_tests/requirements.txt
      script:
        - airflow initdb
        # Add a dummy environment file to make the dag valid
        - echo "prd" > dags/environment.conf
        - coverage run -m pytest integrity_tests/*
    - stage: mock_pipeline_tests
      before_install: 
        - source travis_java_install.sh
      install:
        - pip install -r mock_pipeline_tests/requirements.txt
      script:
        - coverage run -m pytest mock_pipeline_tests/*
